[server]
blog_name = "Your Awesome Blog Name"
author = "You"
description = "Your awesome blog description"
footer_links = { "Home" = "/", "Your Website" = "https://your.website", "Your Other Links" = "https://example.com" }
addr = "0.0.0.0:4444"
domain = "your.domain"

[client]
addr = "http://localhost:4444"
secret = ""
